[features]
seeds = false
skip-lint = false
[programs.devnet]
onchain_voting = "FUCKUQXmg4i4ken7xeYcNLDFtH5NTfs5fZiMahVrNgU6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/baris/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 100000000 tests/**/*.ts"
